[package]
name = "memecoin-proto"
version = "1.0.12"
edition = "2024"

[dependencies]
tonic = "0.12"
prost = "0.13"
serde = { version = "1.0", features = ["derive"] }
[build-dependencies]
tonic-build = "0.12"